### ISSUE TITLE
Checklist 0.1 beta

### ISSUE THREAD

**Issue by ssteinker** [famelo/Bootstrap#3]
### Content
- [ ] remove Lorem Ipsum
- [ ] Check all text's
### Pageload's
- [ ] compressed images
- [ ] check all links
- [ ] check Formdata
- [ ] change Formmail
- [ ] CSS minified
- [ ] Javascript minified
### SEO
- [ ] add Google-Account
- [ ] add Google Analytics
- [ ] submit Google Sitemap
- [ ] add Google Webmaster tools
- [ ] Pagetitle
- [ ] Meta/Keywords
- [ ] robots.txt
- [ ] spoken URLS
### Accessibility ###
- [ ] W3C valides HTML
- [ ] W3C valides JavaScript
- [ ] Custom 404
- [ ] Custom 303
- [ ] Favicon
### Browsercheck's
- [ ] Firefox
- [ ] Opera 
- [ ] Safari
- [ ] IE 7
- [ ] IE 8
- [ ] IE 9
- [ ] IE 10
### stuff
- [ ] clean up code

**Comment by mneuhaus** [comment]
- ie10 muss auch mittlerweile kontrolliert werden
- clean up code? ;D glaubst du doch selber nicht ^^
